package com.example.demo.domen;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

import java.util.Date;

@Entity
@Table(name = "event")
public class EventDTO {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    @NotNull
    private String type;

    @NotNull
    private String description;

    @Column(name="EVENT_DT")
    private Date eventDt;



    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getEventDt() {
        return eventDt;
    }

    public void setEventDt(Date eventDt) {
        this.eventDt = eventDt;
    }

    @Override
    public String toString() {
        return "EventDTO{" +
                "id=" + id +
                ", type='" + type + '\'' +
                ", description='" + description + '\'' +
                ", eventDt=" + eventDt +
                '}';
    }

    public EventDTO(@NotNull String type, @NotNull String description, Date eventDt) {
        this.type = type;
        this.description = description;
        this.eventDt = eventDt;
    }

    public EventDTO() {
    }
}
